from pydantic_settings import BaseSettings
from dotenv import load_dotenv
from functools import lru_cache

load_dotenv()


class ConfigSettings(BaseSettings):
    API_KEY: str = "string"
    CP_SECRET: str = "string"
    DEFAULT_TOKENS_NEW: list[str] = [
        "DFI.Money (YFII)",
        "FIO Protocol (FIO)",
        "Bonfida (FIDA)",
        "Reef (REEF)",
        "Harvest Finance (FARM)",
        "Paris Saint Germain (PSG)",
        "Perpetual Protocol (PERP)",
        "Alien Worlds (TLM)",
        "Radicle (RAD)",
        "Cream Finance (CREAM)",
        "THORChain (RUNE)",
        "Frontier (FRONT)",
        "Acala Token (ACA)",
        "BenQi (QI)",
        "Bancor (BNT)",
        "My Neighbor Alice (ALICE)",
        "Loom Network (LOOM)",
        "WinkLink (WIN)",
        "Bake (BAKE)",
        "Hooked Protocol (HOOK)",
        "Steem (STEEM)",
        "CyberConnect (CYBER)",
        "Sun (SUN)",
        "Hive (HIVE)",
        "Smooth Love Potion (SLP)",
        "Coin98 (C98)",
        "Venus (XVS)",
        "Storj (STORJ)",
        "BabyDoge (BABYDOGE)",
        "Ontology (ONT)",
        "Tellor (TRB)",
        "Harmony (ONE)",
        "Yearn.Finance (YFI)",
        "Jupiter (JUP)",
        "Arkham (ARKM)",
        "Illuvium (ILV)",
        "Basic Attention Token (BAT)",
        "Enjin Coin (ENJ)",
        "Celo (CELO)",
        "Osmosis (OSMO)",
        "Zilliqa (ZIL)",
        "Terra (LUNA)",
        "Memecoin (MEME)",
        "Dash (DASH)",
        "Manta Network (MANTA)",
        "Green Metaverse Token (GMT)",
        "ConstitutionDAO (PEOPLE)",
        "Safepal (SFP)",
        "IoTeX (IOTX)",
        "Kava (KAVA)",
        "Trustwallet (TWT)",
        "1inch (1INCH)",
        "Terra Classic (LUNC)",
        "LayerZero (ZRO)",
        "ApeCoin (APE)",
        "Cake (CAKE)",
        "Compound (COMP)",
        "ZkSync (ZK)",
        "Sats (SATS)",
        "Chiliz (CHZ)",
        "Decentraland (MANA)",
        "Book of Meme (BOME)",
        "Worldcoin (WLD)",
        "MultiversX (EGLD)",
        "The Sandbox (SAND)",
        "Ordi (ORDI)",
        "BitTorrent (BTT)",
        "Gala (GALA)",
        "DYDX (DYDX)",
        "Tezos (XTZ)",
        "EOS (EOS)",
        "Axie Infinity (AXS)",
        "Quant (QNT)",
        "Sei (SEI)",
        "Algorand (ALGO)",
        "Core (CORE)",
        "Celestia (TIA)",
        "Sonic (S)",
        "Pyth Network (PYTH)",
        "Theta Token (THETA)",
        "Floki (FLOKI)",
        "Bonk (BONK)",
        "The Graph (GRT)",
        "AAVE (AAVE)",
        "Dogwifhat (WIF)",
        "Optimism (OP)",
        "Render Token (RENDER)",
        "Injective Protocol (INJ)",
        "Vechain (VET)",
        "Cosmos (ATOM)",
        "Filecoin (FIL)",
        "Stellar Lumens (XLM)",
        "Aptos (APT)",
        "Ethereum Classic (ETC)",
        "Uniswap (UNI)",
        "Internet Computer (ICP)",
        "Pepe (PEPE)",
        "Polygon (MATIC)",
        "Litecoin (LTC)",
        "Near Protocol (NEAR)",
        "Chainlink (LINK)",
        "Polkadot (DOT)",
        "Bitcoin Cash (BCH)",
        "Shiba Inu (SHIB)",
        "Avalanche (AVAX)",
        "Tron (TRX)",
        "Cardano (ADA)",
        "Toncoin (TON)",
        "Dogecoin (DOGE)",
        "Ripple (XRP)",
        "USD Coin (USDC)",
        "Solana (SOL)",
        "Binance (BNB)",
        "Tether (USDT)",
        "Ethereum (ETH)",
        "Bitcoin (BTC)",
        "SuperFarm (SUPER)",
        "Fetch.ai (FET)",
        "Pi (PI)",
        "Hedra (HBAR)",
        "Aixbt (AIXBT)",
        "Ice Open Network (ICE)",
        "Stacks (STX)",
        "Peanut The Squirrel (PNUT)",
        "Official Trum (TRUMP)",
        "Dogs (DOGS)",
        "Sui (SUI)",
    ]


@lru_cache()
def get_settings():
    return ConfigSettings()
